### ISSUE TITLE
hw02 bug? 5.1

### ISSUE THREAD

**Issue by futbol4me** [ccsf-math-108/materials-sp22#2]
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/8358816/152709102-57f5eaff-17c3-41e6-8e32-913c46d1e1ea.png">

since the previous question was about np.diff, it was natural just to use np.diff on this dataset.  the autograder says ok, but if you look at dataset clearly not correct to use np.diff, since elapsed time already implies a time delta.

**Comment by shawnwiggins** [comment]
The public auto grader was just checking `shortest <= average <= longest`. The hidden tests check for other things that reveal that would flag that particular use of `np.diff` as incorrect. I do see your point that it might have felt natural to use `np.diff` after learning about it in Section 4, but it doesn't seem like there is a bug in this problem or with the grader. Thanks for bringing this up for review!
